name: Bump version

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Extract PR title
      id: pr_title
      run: echo "::set-output name=title::${{ github.event.pull_request.title }}"

    - name: Determine bump type
      id: bump_type
      run: |
        pr_title="${{ steps.pr_title.outputs.title }}"
        if [[ "$pr_title" == *"[+major]"* ]]; then
          echo "::set-output name=bump::major"
        elif [[ "$pr_title" == *"[+minor]"* ]]; then
          echo "::set-output name=bump::minor"
        elif [[ "$pr_title" == *"[+patch]"* ]]; then
          echo "::set-output name=bump::patch"
        else
          echo "Error: PR title must contain [+major], [+minor], or [+patch]"
          exit 1

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: L1ZiT
      with:
        bump_level: ${{ steps.bump_type.outputs.bump }}
